export interface Character {
  id: string; name: string; surname: string; country: string; code: string; role: string;
  region: 'Americas' | 'Europe' | 'Asia & Pacific' | 'Middle East & Africa';
  title: string; quote: string; description: string; color: string; index: number;
}
const entries: Omit<Character, 'index'>[] = [
  {id:'trump',name:'Donald Trump',surname:'TRUMP',country:'United States',code:'USA',role:'President',region:'Americas',title:'THE DEALMAKER',quote:'This combo? Tremendous paperwork.',description:'Arrives with a red tie, a long agenda, and absolutely no intention of reading the minutes.',color:'#a93232'},
  {id:'xi',name:'Xi Jinping',surname:'XI JINPING',country:'China',code:'CHN',role:'President / CCP General Secretary',region:'Asia & Pacific',title:'THE LONG GAME',quote:'The five-round plan has been revised to three.',description:'A measured entrance. An immaculate suit. A meeting that could definitely have been an email.',color:'#384b70'},
  {id:'putin',name:'Vladimir Putin',surname:'PUTIN',country:'Russia',code:'RUS',role:'President',region:'Europe',title:'THE POKER FACE',quote:'The table was too long. We moved to the arena.',description:'Keeps the expression unreadable and the conference table at a strictly impractical length.',color:'#414958'},
  {id:'modi',name:'Narendra Modi',surname:'MODI',country:'India',code:'IND',role:'Prime Minister',region:'Asia & Pacific',title:'THE GRAND ENTRANCE',quote:'First, a handshake. Then, the highlight reel.',description:'Brings a signature waistcoat and enough opening remarks to outlast the round timer.',color:'#c99552'},
  {id:'burnham',name:'Andy Burnham',surname:'BURNHAM',country:'United Kingdom',code:'GBR',role:'Prime Minister',region:'Europe',title:'THE NORTHERN ROUND',quote:'Mind the gap. Especially after that backdash.',description:'A fictional summit slot with northern confidence and a remarkably punctual victory speech.',color:'#8c474d'},
  {id:'macron',name:'Emmanuel Macron',surname:'MACRON',country:'France',code:'FRA',role:'President',region:'Europe',title:'THE ENCORE',quote:'One more round. For the European project.',description:'The sleeves are rolled, the cameras are ready, and the closing statement has three encores.',color:'#384f80'},
  {id:'merz',name:'Friedrich Merz',surname:'MERZ',country:'Germany',code:'DEU',role:'Chancellor',region:'Europe',title:'THE BALANCE SHEET',quote:'Your guard has a structural deficit.',description:'Every opening gets audited. Every whiff is entered in the meeting minutes.',color:'#55586a'},
  {id:'meloni',name:'Giorgia Meloni',surname:'MELONI',country:'Italy',code:'ITA',role:'Prime Minister',region:'Europe',title:'THE FINAL WORD',quote:'The agenda says espresso, then overtime.',description:'A stare across the summit table becomes an entire pre-match cinematic.',color:'#464964'},
  {id:'takaichi',name:'Sanae Takaichi',surname:'TAKAICHI',country:'Japan',code:'JPN',role:'Prime Minister',region:'Asia & Pacific',title:'THE TEMPO SETTER',quote:'The next item on the agenda is a drum solo.',description:'An immaculate blazer meets a perfectly timed entrance cue. The band has been warned.',color:'#3e6985'},
  {id:'mbs',name:'Mohammed bin Salman',surname:'BIN SALMAN',country:'Saudi Arabia',code:'SAU',role:'Crown Prince / Prime Minister',region:'Middle East & Africa',title:'THE BIG PICTURE',quote:'The rematch will have its own skyline.',description:'A sweeping entrance, a grand proposal, and an arena renovation planned before round two.',color:'#c0a577'},
  {id:'erdogan',name:'Recep Tayyip Erdoğan',surname:'ERDOĞAN',country:'Türkiye',code:'TUR',role:'President',region:'Middle East & Africa',title:'THE EXTRA SESSION',quote:'This meeting is going into extra time.',description:'The gavel is down. The press are waiting. The closing remarks are still loading.',color:'#6f4553'},
  {id:'lula',name:'Luiz Inácio Lula da Silva',surname:'LULA',country:'Brazil',code:'BRA',role:'President',region:'Americas',title:'THE COMEBACK TOUR',quote:'I brought snacks for the deciding round.',description:'An old hand at the summit circuit, with a fresh set of cue cards and a very full itinerary.',color:'#40715d'},
  {id:'carney',name:'Mark Carney',surname:'CARNEY',country:'Canada',code:'CAN',role:'Prime Minister',region:'Americas',title:'THE STRESS TEST',quote:'Your stamina forecast has been downgraded.',description:'Calm in the briefing. Calm in the arena. Probably running a spreadsheet between rounds.',color:'#535f7c'},
  {id:'sheinbaum',name:'Claudia Sheinbaum',surname:'SHEINBAUM',country:'Mexico',code:'MEX',role:'President',region:'Americas',title:'THE EQUATION',quote:'I checked the numbers. That was a whiff.',description:'A precise entrance and a carefully annotated plan. The podium has been peer-reviewed.',color:'#93465e'},
  {id:'lee',name:'Lee Jae Myung',surname:'LEE JAE MYUNG',country:'South Korea',code:'KOR',role:'President',region:'Asia & Pacific',title:'THE NEXT ROUND',quote:'Please submit your combo in triplicate.',description:'The glasses are straight. The briefing is complete. The overtime request is pending.',color:'#3b617d'},
  {id:'prabowo',name:'Prabowo Subianto',surname:'PRABOWO',country:'Indonesia',code:'IDN',role:'President',region:'Asia & Pacific',title:'THE VICTORY STEP',quote:'The victory dance is still in rehearsal.',description:'A crisp jacket and an entrance with its own rhythm. The protocol team is improvising.',color:'#b1a38c'},
  {id:'ramaphosa',name:'Cyril Ramaphosa',surname:'RAMAPHOSA',country:'South Africa',code:'ZAF',role:'President',region:'Middle East & Africa',title:'THE NEGOTIATOR',quote:'Let us form a committee on that uppercut.',description:'Brings a measured smile and a proposal to extend the coffee break by one more round.',color:'#486157'},
  {id:'albanese',name:'Anthony Albanese',surname:'ALBANESE',country:'Australia',code:'AUS',role:'Prime Minister',region:'Asia & Pacific',title:'THE AWAY GAME',quote:'Long flight. Short opening statement.',description:'Travels halfway around the planet, then asks where the decent coffee is.',color:'#5c6478'},
  {id:'milei',name:'Javier Milei',surname:'MILEI',country:'Argentina',code:'ARG',role:'President',region:'Americas',title:'THE WILD CARD',quote:'The hair has its own collision box. Allegedly.',description:'Maximum volume, dramatic hair, and an entrance that requires a separate sound check.',color:'#4f4167'},
  {id:'von-der-leyen',name:'Ursula von der Leyen',surname:'VON DER LEYEN',country:'European Union',code:'EUR',role:'European Commission President',region:'Europe',title:'THE CONSENSUS',quote:'This combo has cleared all twenty-seven reviews.',description:'A sharply tailored jacket and a rulebook with more annexes than the arena has seats.',color:'#7184a5'},
  {id:'kim',name:'Kim Jong Un',surname:'KIM JONG UN',country:'North Korea',code:'PRK',role:'State Affairs President / Supreme Leader',region:'Asia & Pacific',title:'THE UNANNOUNCED ENTRY',quote:'My entrance animation needs another entrance.',description:'A high collar, a dramatic pause, and an opening ceremony that has already run over time.',color:'#3b4843'},
];
export const characters: Character[] = entries.map((character,index)=>({...character,index}));
export const rosterNotice = 'User-selected fictional tournament roster. Role labels follow the supplied cast list and are not a verified directory of current officeholders. All quotes are original game fiction.';
