import { publicAssetUrl } from './assets';
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, ChevronDown, Cpu, Crosshair, Download, Globe2, HelpCircle, History, Keyboard, LoaderCircle, Monitor, Search, Settings2, Shield, Sparkles, Swords, Volume2, VolumeX, X } from 'lucide-react';
import { characters, rosterNotice } from '../../../packages/content/src';
import type { Character } from '../../../packages/content/src';
import { fighterProfileForCharacter, signatureForCharacter } from '../../../packages/combat-core/src';
import type { Difficulty, SpecialId } from '../../../packages/combat-core/src';
import { LayaWorkerController } from './ai';
import type { LoadProgress } from './ai';
import { Portrait } from './components/Portrait';
import { FighterStats } from './components/FighterStats';
import { BrandLogo } from './components/BrandLogo';
import { ArenaRadio } from './components/ArenaRadio';
import { Modal } from './components/Modal';
import { Match } from './components/Match';
import { clearReplays, downloadReplay, readReplays } from './game/replay';
import type { ReplayData } from './game/replay';
import { bindingLabels, defaultBindings, keyLabel } from './game/input';
import { readSettings, storeSettings } from './settings';
import type { Settings } from './settings';

const asset=(path:string)=>publicAssetUrl(`assets/${path}`);
export default function App(){
  const [screen,setScreen]=useState<'boot'|'select'|'fight'|'results'>('boot');
  const [bootState,setBootState]=useState<'idle'|'loading'|'error'>('idle');
  const [progress,setProgress]=useState<LoadProgress>({progress:0,stage:'Ready to initialize',detail:'The model runs on your device.'});
  const [loadError,setLoadError]=useState('');
  const [mode,setMode]=useState<'laya'|'baseline'>('baseline');
  const controller=useRef<LayaWorkerController|null>(null);
  const abort=useRef<AbortController|null>(null);
  const [player,setPlayer]=useState(characters[0]); const [opponent,setOpponent]=useState(characters[1]);
  const [activeSlot,setActiveSlot]=useState<0|1>(0);
  const [difficulty,setDifficulty]=useState<Difficulty>('standard');
  const [filter,setFilter]=useState('All delegates');const [query,setQuery]=useState('');
  const [settings,setSettings]=useState<Settings>(readSettings);
  const [modal,setModal]=useState<'settings'|'manual'|'about'|'replays'|null>(null);
  const [remap,setRemap]=useState<string|null>(null);
  const [training,setTraining]=useState(false);
  const [replay,setReplay]=useState<ReplayData|undefined>();
  const specials:[SpecialId,SpecialId]=replay?.specials??[signatureForCharacter(player.id).id,signatureForCharacter(opponent.id).id];
  const [result,setResult]=useState<ReplayData|null>(null);
  const [matchKey,setMatchKey]=useState(0);
  useEffect(()=>storeSettings(settings),[settings]);
  useEffect(()=>()=>{abort.current?.abort();controller.current?.dispose();},[]);
  useEffect(()=>{if(!remap)return;const listener=(e:KeyboardEvent)=>{e.preventDefault();if(e.code==='Escape'){setRemap(null);return;}if(['KeyC'].includes(e.code))return;setSettings(s=>{const bindings={...s.bindings};const other=Object.keys(bindings).find(k=>bindings[k]===e.code);if(other)bindings[other]=bindings[remap];bindings[remap]=e.code;return {...s,bindings};});setRemap(null);};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[remap]);
  async function loadLaya(){
    abort.current?.abort();controller.current?.dispose();
    const attempt=new AbortController();const candidate=new LayaWorkerController();
    abort.current=attempt;controller.current=candidate;setBootState('loading');setLoadError('');
    const current=()=>abort.current===attempt&&!attempt.signal.aborted&&controller.current===candidate;
    try{await candidate.load(value=>{if(current())setProgress(value);},attempt.signal);if(!current())return;setMode('laya');setBootState('idle');setScreen('select');}
    catch(error){if(!current())return;setBootState('error');setLoadError(error instanceof Error?error.message:'Unable to initialize Laya.');}
  }
  function baseline(){abort.current?.abort();controller.current?.dispose();controller.current=null;setMode('baseline');setBootState('idle');setScreen('select');}
  function start(isTraining=false){setReplay(undefined);setTraining(isTraining);setMatchKey(k=>k+1);setScreen('fight');}
  function watch(item:ReplayData){setPlayer(characters.find(x=>x.id===item.player)??characters[0]);setOpponent(characters.find(x=>x.id===item.opponent)??characters[1]);setTraining(false);setReplay(item);setModal(null);setMatchKey(k=>k+1);setScreen('fight');}
  const visible=characters.filter(c=>(filter==='All delegates'||c.region===filter)&&`${c.name} ${c.country}`.toLowerCase().includes(query.toLowerCase()));
  const selected=activeSlot===0?player:opponent;
  return <div className={`app ${settings.reducedMotion?'reduced-motion':''}`}>
    <header className="site-header">
      <button className="brand" aria-label="World Summit Tournament home" onClick={()=>{if(screen!=='fight')setScreen(mode==='laya'||screen!=='boot'?'select':'boot');}}><BrandLogo decorative/><span className="brand-name">WORLD SUMMIT<br/>TOURNAMENT</span></button>
      <nav aria-label="Main navigation"><button className={screen==='select'?'active':''} onClick={()=>screen==='boot'?baseline():setScreen('select')} disabled={screen==='fight'}>THE ARENA</button><button onClick={()=>setModal('manual')}>FIELD MANUAL</button><button onClick={()=>setModal('replays')}>REPLAYS</button></nav>
      <div className="header-right"><span className="build-tag">EARLY ACCESS <span>0.1</span></span><button className="icon-button" aria-label={settings.muted?'Unmute sound':'Mute sound'} onClick={()=>setSettings(s=>({...s,muted:!s.muted}))}>{settings.muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button><button className="icon-button" aria-label="Settings" onClick={()=>setModal('settings')}><Settings2 size={18}/></button></div>
    </header>
    <div className="arena-radio-bar"><ArenaRadio muted={settings.muted} volume={settings.radioVolume} onVolumeChange={radioVolume=>setSettings(s=>({...s,radioVolume}))}/></div>

    {screen==='boot'&&<main className="boot-screen" style={{backgroundImage:`url(${asset('summit-showdown.png')})`}}>
      <div className="boot-shade"/>
      <div className="boot-content"><div className="eyebrow"><span className="tiny-line"/> THE WORLD IS YOUR ARENA</div><h1>DIPLOMACY<br/>ENDS <em>HERE.</em></h1><p className="boot-subtitle">Twenty-one delegates. One very different summit.<br/>The next round of negotiations is personal.</p>
        <div className="boot-panel"><div className="boot-panel-title"><Cpu size={19}/><span>YOUR BROWSER. HYBRID OPPONENT.</span><span className="tag">CLIENT SIDE</span></div>
          <p>This game uses your GPU for graphics and Laya. The model download is about 413 MB and needs a browser with WebGPU and substantial memory. Genuine Laya decisions inform a fast local combat controller between model inferences, so the opponent stays active on your device.</p>
          <p className="model-caveat">Laya is an experimental hybrid opponent: this general model has not been trained for fighting and can still choose passive tactics. The local combat controller keeps the round moving between Laya decisions. Choose baseline practice if you want the transparent arcade controller.</p>
          {bootState==='loading'?<div className="model-progress" aria-live="polite"><div><span>{progress.stage}</span><strong>{Math.round(progress.progress*100)}%</strong></div><progress max={1} value={progress.progress}/><small>{progress.detail}</small><button className="text-button" onClick={()=>{abort.current?.abort();setBootState('idle');}}>Cancel loading</button></div>:<>
            {bootState==='error'&&<div className="load-error" role="alert"><strong>Laya could not initialize</strong><p>{loadError}</p><span>Practice is available with a clearly labelled baseline controller.</span></div>}
            <button className="primary-button full" onClick={loadLaya}><Cpu size={18}/>{bootState==='error'?'RETRY HYBRID LAYA INITIALIZATION':'INITIALIZE HYBRID LAYA'}<ArrowRight size={20}/></button>
            <button className="baseline-button" onClick={baseline}>Enter baseline practice <ArrowUpRight size={16}/></button>
          </>}
          <div className="boot-points"><span><Shield size={13}/> No account</span><span><Monitor size={13}/> Runs locally</span><span><Keyboard size={13}/> Keyboard + gamepad</span></div>
        </div>
      </div><div className="boot-side-label">THE SUMMIT / FICTIONAL ARCADE SATIRE</div><div className="boot-bottom"><span>NO SPEECHES. JUST COMBOS.</span><button onClick={()=>setModal('about')}>HOW THE AI WORKS <ArrowUpRight size={15}/></button></div>
    </main>}

    {screen==='select'&&<main className="selection">
      <div className="section-heading"><div><div className="eyebrow">EXHIBITION / THE SUMMIT</div><h1>CHOOSE YOUR <em>DELEGATE.</em></h1></div><div className="controller-status"><span className={`status-dot ${mode==='baseline'?'amber':''}`}/><div><strong>{mode==='laya'?'LAYA + COMBAT CONTROLLER':'BASELINE PRACTICE'}</strong><small>{mode==='laya'?'Laya decisions · local planner active':'Heuristic opponent · no model loaded'}</small></div><button className="icon-button" aria-label="About the AI controller" onClick={()=>setModal('about')}><HelpCircle size={17}/></button></div></div>
      <div className="fighter-tabs" role="tablist" aria-label="Choose which fighter to assign"><button type="button" role="tab" aria-selected={activeSlot===0} className={`fighter-tab player-tab ${activeSlot===0?'active':''}`} onClick={()=>setActiveSlot(0)}><span className="fighter-tab-art"><Portrait character={player}/></span><span className="fighter-tab-copy"><span className="fighter-tab-label">YOUR FIGHTER</span><strong>{player.name}</strong><small>{activeSlot===0?'SELECTING NEXT ROSTER PICK':'Click to choose your delegate'}</small></span><Check size={17}/></button><button type="button" role="tab" aria-selected={activeSlot===1} className={`fighter-tab ai-tab ${activeSlot===1?'active':''}`} onClick={()=>setActiveSlot(1)}><span className="fighter-tab-art"><Portrait character={opponent}/></span><span className="fighter-tab-copy"><span className="fighter-tab-label">AI FIGHTER</span><strong>{opponent.name}</strong><small>{activeSlot===1?'CHOOSE AI FIGHTER · NEXT ROSTER PICK':'Click to choose AI fighter'}</small></span><Check size={17}/></button></div>
      <section className="matchup" aria-label="Selected fighters">
        <FighterPanel character={player} side={0} active={activeSlot===0} onSelect={()=>setActiveSlot(0)}/>
        <div className="versus-block"><div className="versus-line"/><span>VS</span><small>BEST OF THREE</small><div className="versus-line"/></div>
        <FighterPanel character={opponent} side={1} active={activeSlot===1} onSelect={()=>setActiveSlot(1)}/>
      </section>
      <section className="roster-section" aria-label="Character roster">
        <div className="roster-toolbar"><div className="roster-heading"><h2>THE DELEGATION</h2><span>{characters.length} FIGHTERS</span></div><div className="roster-tools"><label className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a delegate" aria-label="Search characters"/></label><label className="filter-box"><Globe2 size={16}/><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filter by region">{['All delegates','Americas','Europe','Asia & Pacific','Middle East & Africa'].map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label></div></div>
        <div className="roster-hint">NEXT ROSTER PICK → <span className={activeSlot===0?'cyan':'orange'}>{activeSlot===0?'YOUR FIGHTER':'AI FIGHTER'}</span><span className="hint-divider"/> Select either tab above, then click any portrait. Same delegate may be chosen twice.</div>
        <div className="roster-grid">{visible.map(character=><button key={character.id} className={`roster-card ${player.id===character.id?'is-player':''} ${opponent.id===character.id?'is-opponent':''}`} onClick={()=>activeSlot===0?setPlayer(character):setOpponent(character)} aria-label={`Select ${character.name} for ${activeSlot===0?'player':'AI'}`} aria-pressed={selected.id===character.id}><Portrait character={character}/><span className="roster-card-shade"/><span className="country-code">{character.code}</span>{(player.id===character.id||opponent.id===character.id)&&<span className="slot-marker">{player.id===character.id?'P1':''}{player.id===character.id&&opponent.id===character.id?' / ':''}{opponent.id===character.id?'AI':''}</span>}<span className="roster-card-name">{character.surname}</span></button>)}</div>
        {visible.length===0&&<div className="empty-state">No delegates found. Try a name or country.</div>}
      </section>
      <section className="launch-bar"><div className="arena-info"><span className="arena-thumb" style={{backgroundImage:`url(${asset('summit-showdown.png')})`}}/><div><small>YOUR STAGE</small><strong>THE SUMMIT</strong><span>60-second rounds · Balanced builds</span></div></div><div className="difficulty-control"><label htmlFor="difficulty">OPPONENT DIFFICULTY</label><select id="difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value as Difficulty)}><option value="beginner">Beginner</option><option value="standard">Standard</option><option value="expert">Expert</option></select></div><button className="secondary-button training-button" onClick={()=>start(true)}><Crosshair size={16}/> TRAINING</button><button className="primary-button fight-button" onClick={()=>start()}><Swords size={19}/> ENTER THE ARENA <ArrowRight size={21}/></button></section>
      <div className="selection-footnote"><span>Different strengths. Shared stat budget. Every delegate has a unique signature.</span><button onClick={()=>setModal('manual')}>Learn the controls <ArrowUpRight size={14}/></button></div>
    </main>}

    {screen==='fight'&&<Match key={matchKey} player={player} opponent={opponent} specials={specials} difficulty={difficulty} mode={mode} controller={controller.current} settings={settings} overlayOpen={modal!==null} training={training} replay={replay} onExit={()=>setScreen('select')} onEnd={item=>{setResult(item);setScreen('results');}} onSettings={()=>setModal('settings')}/>}
    {screen==='results'&&result&&<main className="results-screen"><div className="eyebrow">THE SUMMIT / MATCH REPORT</div><h1>{result.winner==='draw'?'A DIPLOMATIC DRAW.':result.winner===0?'MOTION CARRIED.':'MOTION DENIED.'}</h1><p>{result.winner==='draw'?'The delegation has agreed to disagree.':result.winner===0?'Your closing argument landed.':'The opponent has the floor. There’s always a rematch.'}</p><div className="result-pair"><Portrait character={player}/><div><span>{result.wins[0]} <i>—</i> {result.wins[1]}</span><small>{result.controller==='laya'?'LAYA + COMBAT':result.controller.toUpperCase()} · RECORDED MATCH</small></div><Portrait character={opponent}/></div><div className="result-actions"><button className="primary-button" onClick={()=>start()}>RUN IT BACK <ArrowRight size={19}/></button><button className="secondary-button" onClick={()=>watch(result)}><History size={18}/> WATCH REPLAY</button><button className="secondary-button" onClick={()=>downloadReplay(result)}><Download size={17}/> REPLAY DATA</button><button className="text-button" onClick={()=>setScreen('select')}>Change delegates</button></div></main>}

    <footer className="site-footer"><span><span className="fiction-mark"/> FICTIONAL ARCADE SATIRE</span><span>No real quotes. No political stats. Just a game.</span><button onClick={()=>setModal('about')}>ABOUT WST <ArrowUpRight size={12}/></button></footer>
    {modal==='settings'&&<Modal title="SETTINGS" onClose={()=>{setModal(null);setRemap(null);}}><div className="settings-content"><label className="setting-row"><span>Effects volume <small>Recorded foley + signature effects</small></span><input aria-label="Effects volume" type="range" min="0" max="1" step="0.05" value={settings.volume} onChange={e=>setSettings(s=>({...s,volume:Number(e.target.value)}))}/></label><label className="setting-row"><span>Mute all audio</span><input type="checkbox" checked={settings.muted} onChange={e=>setSettings(s=>({...s,muted:e.target.checked}))}/></label><label className="setting-row"><span>Reduced effects <small>Less motion; applies to your next match</small></span><input type="checkbox" checked={settings.reducedMotion} onChange={e=>setSettings(s=>({...s,reducedMotion:e.target.checked}))}/></label><label className="setting-row"><span>Graphics quality <small>Applies to your next match</small></span><select value={settings.quality} onChange={e=>setSettings(s=>({...s,quality:e.target.value as 'high'|'low'}))}><option value="high">High</option><option value="low">Low power</option></select></label><h3>KEY BINDINGS</h3><p className="muted">Select a key to remap it. Escape cancels. C opens AI Cam; Escape pauses.</p><div className="bindings-grid">{Object.entries(bindingLabels).map(([key,label])=><button key={key} className={remap===key?'binding listening':'binding'} onClick={()=>setRemap(key)}><span>{label}</span><kbd>{remap===key?'Press key…':keyLabel(settings.bindings[key])}</kbd></button>)}</div><button className="text-button" onClick={()=>setSettings(s=>({...s,bindings:{...defaultBindings}}))}>Restore default keys</button></div></Modal>}
    {modal==='manual'&&<Modal title="THE FIELD MANUAL" wide onClose={()=>setModal(null)}><div className="manual-grid"><div><div className="eyebrow">01 / GET MOVING</div><h3>GOOD FOOTWORK. BAD DIPLOMACY.</h3><p>Move into striking distance before attacking. Your stamina returns while resting or guarding; committed attacks must finish before your next action.</p><div className="controls-list">{Object.entries(bindingLabels).map(([key,label])=><div key={key}><span>{label}</span><kbd>{keyLabel(settings.bindings[key])}</kbd></div>)}</div></div><div><div className="eyebrow">02 / MAKE YOUR CASE</div><h3>READ THE ROOM.</h3><ul className="manual-tips"><li><strong>Mix high and low.</strong> Down + light is a body punch; down + heavy is a low kick. Forward + heavy is an overhead.</li><li><strong>Use your guard.</strong> Standing guard stops high, mid, and overhead. Crouching guard stops low and mid.</li><li><strong>Break the stalemate.</strong> Throws beat guard at close range. Press throw during capture to break free.</li><li><strong>Make it a combo.</strong> On hit, chain light → body → heavy. Up to three hits, with diminishing damage.</li><li><strong>Pick your moment.</strong> Veto parry catches high, mid, and overhead strikes. Build meter through combat. A full meter unlocks your delegate’s unique signature.</li></ul><div className="gamepad-note"><Keyboard size={20}/><p>Gamepad: left stick to move/crouch; A jump, X light, B heavy, Y special; LB parry, RB guard, LT throw, RT dash.</p></div><p className="muted">Desktop fighting supported. Touch controls are experimental. Escape pauses; switching tabs automatically pauses the match.</p></div></div></Modal>}
    {modal==='about'&&<Modal title="BEHIND THE SUMMIT" onClose={()=>setModal(null)}><div className="about-content"><div className="about-badge"><Cpu size={28}/><span>LOCAL FIRST.<br/>FAIR BY DESIGN.</span></div><p>WST is a fictional fighting game. The combat simulation runs at 60 ticks per second on your device. Character identity never enters the AI’s observation, and each delegate has a distinct gameplay build with the same total stat budget. Power, speed, health, stamina and recovery trade off against each other, alongside a fixed signature move.</p><h3>WHAT CONTROLS THE OPPONENT?</h3><p>This build includes an ONNX export of the real Laya checkpoint. It downloads model files, initializes the browser runtime, and warms up inference before selection. Genuine Laya decisions inform a fast local combat controller between model inferences, keeping the opponent active while the combat simulation runs independently. This general checkpoint has not been trained for fighting; it can still choose passive tactics, so the hybrid remains experimental.</p><p><strong>{mode==='laya'?'Laya + combat controller is active on this device.':'This session uses baseline practice.'}</strong> The baseline is a transparent heuristic controller. It is not Laya. Difficulty changes perception delay, never damage or hidden access to your inputs.</p><button className="secondary-button full" onClick={()=>{setModal(null);setScreen('boot');}}>OPEN MODEL INITIALIZATION <ArrowUpRight size={16}/></button><h3>FICTION & ART</h3><p>{rosterNotice}</p><p>Portraits and key art were generated with imagegen. Every delegate uses an individual 24-pose, high-detail animation set inside a 2.5D arena. These are rendered sprites, not rigged 3D likeness meshes. Audio combines recorded CC0 foley from Kenney with original synthesized signature effects, with no cloned voices.</p><div className="about-links"><a href="https://github.com/NandhaKishorM/laya" target="_blank" rel="noreferrer">Laya source <ArrowUpRight size={14}/></a><a href="https://github.com/cristianexer/WST" target="_blank" rel="noreferrer">Project repository <ArrowUpRight size={14}/></a></div></div></Modal>}
    {modal==='replays'&&<Modal title="THE REPLAY ROOM" onClose={()=>setModal(null)}><p className="muted">Your last five matches from this combat version stay on this device. Replays use recorded inputs and never query the AI again.</p><div className="replay-list">{readReplays().length?readReplays().map(item=><div className="replay-item" key={item.id}><div><strong>{characters.find(c=>c.id===item.player)?.surname} <span>VS</span> {characters.find(c=>c.id===item.opponent)?.surname}</strong><small>{new Date(item.createdAt).toLocaleString()} · {item.controller}</small></div><button className="icon-button" onClick={()=>watch(item)} aria-label="Watch saved replay"><History size={19}/></button><button className="icon-button" onClick={()=>downloadReplay(item)} aria-label="Download saved replay"><Download size={18}/></button></div>):<div className="empty-state"><History size={30}/><p>No summit history yet.<br/>Finish a match to save its replay.</p></div>}</div><button className="text-button" onClick={()=>{clearReplays();setModal(null);}}>Delete saved replays</button></Modal>}
  </div>;
}
function FighterPanel({character,side,active,onSelect}:{character:Character;side:0|1;active:boolean;onSelect:()=>void}){
  const signature=signatureForCharacter(character.id);
  return <article className={`fighter-panel ${side===1?'opponent-panel':'player-panel'} ${active?'editing':''}`}><button className="fighter-select-area" onClick={onSelect} aria-label={`Choose ${side===0?'player':'AI opponent'} character`}><Portrait character={character}/><span className="fighter-vignette"/><span className="fighter-slot"><span className="status-dot"/>{side===0?'01 / YOUR DELEGATE':'02 / AI OPPONENT'}{active&&<span className="editing-tag">SELECTING</span>}</span><span className="fighter-identity"><span className="fighter-country">{character.country} <i>/</i> {character.code}</span><span className="fighter-title">{character.title}</span><strong>{character.surname}</strong><span className="fighter-role">{character.role}</span></span><span className="switch-character"><Crosshair size={15}/> CHANGE DELEGATE</span></button><div className="fighter-details"><p className="fighter-quote">“{character.quote}” <span>FICTIONAL QUIP</span></p><p className="fighter-description">{character.description}</p><FighterStats characterId={character.id}/><div className="signature-detail"><span><Sparkles size={14}/> UNIQUE SIGNATURE</span><strong style={{color:signature.color}}>{signature.name}</strong><p>{signature.description}</p><small>{signature.startup}f startup · {signature.kind==='shield'?'ONE-STRIKE DEFENSE':`${Math.round(signature.damage*fighterProfileForCharacter(character.id).stats.power/100)} damage · ${signature.reach.toFixed(2)} m`} · 100 meter</small></div></div></article>;
}
